services:
  scraper:
    build:
      context: .
      dockerfile: Dockerfile
    image: scraper:latest
    container_name: scraper
    volumes:
      - ${PWD}/info.json:/app/info.json
    restart: unless-stopped
